/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
export interface ChecklistItem {
  id?: number;
  checklistId?: number;
  googlePlaceId?: string;
  addedById?: number;
  latitude?: number;
  longitude?: number;
}

export interface LocationLog {
  id?: number;
  tripId?: number;
  latitude?: number;
  longitude?: number;
  recordedAt?: string;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

export interface SseEmitter {
  timeout?: number;
}

export interface DriverTripHistory {
  userId?: number;
  trips?: TripHistory[];
}

export interface LocationLogDTO {
  latitude?: number;
  longitude?: number;
}

export interface TripHistory {
  tripId?: number;
  logs?: LocationLogDTO[];
}

export interface User {
  id?: number;
  name?: string;
  phoneNumber?: string;
  passwordHash?: string;
}

export interface Checklist {
  id?: number;
  name?: string;
  fleetId?: number;
  driverId?: number;
}

export type RegisterWorkerBody = {[key: string]: string};

export type RegisterWorker200 = { [key: string]: unknown };

export type CreateChecklistParams = {
name: string;
};

export type CreateChecklist200 = { [key: string]: unknown };

export type AssignDriver200 = { [key: string]: unknown };

export type AddChecklistItems200 = { [key: string]: unknown };

export type StartTrip200 = { [key: string]: unknown };

export type LogLocation200 = { [key: string]: unknown };

export type EndTrip200 = { [key: string]: unknown };

export type DeleteChecklistItems200 = { [key: string]: unknown };

export type AddChecklistItems1200 = { [key: string]: unknown };

export type LogLocationBatch200 = { [key: string]: unknown };

export type Login200 = { [key: string]: unknown };

export type StreamDriverLocationParams = {
userId: number;
};

export type GetHistoryParams = {
userIds: number[];
start: string;
end: string;
};

export type DeleteChecklist200 = { [key: string]: unknown };

export type DeleteChecklistItems1200 = { [key: string]: unknown };

export const registerWorker = (
    registerWorkerBody: RegisterWorkerBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterWorker200>(
      {url: `/api/manager/locations/register-worker`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerWorkerBody, signal
    },
      );
    }
  


export const getRegisterWorkerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext> => {

const mutationKey = ['registerWorker'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWorker>>, {data: RegisterWorkerBody}> = (props) => {
          const {data} = props ?? {};

          return  registerWorker(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWorkerMutationResult = NonNullable<Awaited<ReturnType<typeof registerWorker>>>
    export type RegisterWorkerMutationBody = RegisterWorkerBody
    export type RegisterWorkerMutationError = unknown

    export const useRegisterWorker = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerWorker>>,
        TError,
        {data: RegisterWorkerBody},
        TContext
      > => {

      const mutationOptions = getRegisterWorkerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const createChecklist = (
    params: CreateChecklistParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateChecklist200>(
      {url: `/api/manager/locations/create-checklist`, method: 'POST',
        params, signal
    },
      );
    }
  


export const getCreateChecklistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChecklist>>, TError,{params: CreateChecklistParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createChecklist>>, TError,{params: CreateChecklistParams}, TContext> => {

const mutationKey = ['createChecklist'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChecklist>>, {params: CreateChecklistParams}> = (props) => {
          const {params} = props ?? {};

          return  createChecklist(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateChecklistMutationResult = NonNullable<Awaited<ReturnType<typeof createChecklist>>>
    
    export type CreateChecklistMutationError = unknown

    export const useCreateChecklist = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChecklist>>, TError,{params: CreateChecklistParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createChecklist>>,
        TError,
        {params: CreateChecklistParams},
        TContext
      > => {

      const mutationOptions = getCreateChecklistMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const assignDriver = (
    checklistId: number,
    driverId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AssignDriver200>(
      {url: `/api/manager/locations/checklist/${checklistId}/assign-driver/${driverId}`, method: 'POST', signal
    },
      );
    }
  


export const getAssignDriverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{checklistId: number;driverId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{checklistId: number;driverId: number}, TContext> => {

const mutationKey = ['assignDriver'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignDriver>>, {checklistId: number;driverId: number}> = (props) => {
          const {checklistId,driverId} = props ?? {};

          return  assignDriver(checklistId,driverId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignDriverMutationResult = NonNullable<Awaited<ReturnType<typeof assignDriver>>>
    
    export type AssignDriverMutationError = unknown

    export const useAssignDriver = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{checklistId: number;driverId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignDriver>>,
        TError,
        {checklistId: number;driverId: number},
        TContext
      > => {

      const mutationOptions = getAssignDriverMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const addChecklistItems = (
    checklistId: number,
    checklistItem: ChecklistItem[],
 signal?: AbortSignal
) => {
      
      
      return customInstance<AddChecklistItems200>(
      {url: `/api/manager/locations/checklist/${checklistId}/add-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checklistItem, signal
    },
      );
    }
  


export const getAddChecklistItemsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext> => {

const mutationKey = ['addChecklistItems'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addChecklistItems>>, {checklistId: number;data: ChecklistItem[]}> = (props) => {
          const {checklistId,data} = props ?? {};

          return  addChecklistItems(checklistId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddChecklistItemsMutationResult = NonNullable<Awaited<ReturnType<typeof addChecklistItems>>>
    export type AddChecklistItemsMutationBody = ChecklistItem[]
    export type AddChecklistItemsMutationError = unknown

    export const useAddChecklistItems = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addChecklistItems>>,
        TError,
        {checklistId: number;data: ChecklistItem[]},
        TContext
      > => {

      const mutationOptions = getAddChecklistItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const startTrip = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<StartTrip200>(
      {url: `/api/driver/locations/start`, method: 'POST', signal
    },
      );
    }
  


export const getStartTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext> => {

const mutationKey = ['startTrip'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startTrip>>, void> = () => {
          

          return  startTrip()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartTripMutationResult = NonNullable<Awaited<ReturnType<typeof startTrip>>>
    
    export type StartTripMutationError = unknown

    export const useStartTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startTrip>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStartTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const logLocation = (
    locationLog: LocationLog,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LogLocation200>(
      {url: `/api/driver/locations/log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: locationLog, signal
    },
      );
    }
  


export const getLogLocationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext> => {

const mutationKey = ['logLocation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logLocation>>, {data: LocationLog}> = (props) => {
          const {data} = props ?? {};

          return  logLocation(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogLocationMutationResult = NonNullable<Awaited<ReturnType<typeof logLocation>>>
    export type LogLocationMutationBody = LocationLog
    export type LogLocationMutationError = unknown

    export const useLogLocation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logLocation>>,
        TError,
        {data: LocationLog},
        TContext
      > => {

      const mutationOptions = getLogLocationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const endTrip = (
    tripId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<EndTrip200>(
      {url: `/api/driver/locations/end/${tripId}`, method: 'POST', signal
    },
      );
    }
  


export const getEndTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext> => {

const mutationKey = ['endTrip'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof endTrip>>, {tripId: number}> = (props) => {
          const {tripId} = props ?? {};

          return  endTrip(tripId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EndTripMutationResult = NonNullable<Awaited<ReturnType<typeof endTrip>>>
    
    export type EndTripMutationError = unknown

    export const useEndTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof endTrip>>,
        TError,
        {tripId: number},
        TContext
      > => {

      const mutationOptions = getEndTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const deleteChecklistItems = (
    checklistId: number,
    itemId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DeleteChecklistItems200>(
      {url: `/api/driver/locations/checklist/${checklistId}/delete-item/${itemId}`, method: 'POST', signal
    },
      );
    }
  


export const getDeleteChecklistItemsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems>>, TError,{checklistId: number;itemId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems>>, TError,{checklistId: number;itemId: number}, TContext> => {

const mutationKey = ['deleteChecklistItems'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChecklistItems>>, {checklistId: number;itemId: number}> = (props) => {
          const {checklistId,itemId} = props ?? {};

          return  deleteChecklistItems(checklistId,itemId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChecklistItemsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChecklistItems>>>
    
    export type DeleteChecklistItemsMutationError = unknown

    export const useDeleteChecklistItems = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems>>, TError,{checklistId: number;itemId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChecklistItems>>,
        TError,
        {checklistId: number;itemId: number},
        TContext
      > => {

      const mutationOptions = getDeleteChecklistItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const addChecklistItems1 = (
    checklistId: number,
    checklistItem: ChecklistItem[],
 signal?: AbortSignal
) => {
      
      
      return customInstance<AddChecklistItems1200>(
      {url: `/api/driver/locations/checklist/${checklistId}/add-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checklistItem, signal
    },
      );
    }
  


export const getAddChecklistItems1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems1>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems1>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext> => {

const mutationKey = ['addChecklistItems1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addChecklistItems1>>, {checklistId: number;data: ChecklistItem[]}> = (props) => {
          const {checklistId,data} = props ?? {};

          return  addChecklistItems1(checklistId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddChecklistItems1MutationResult = NonNullable<Awaited<ReturnType<typeof addChecklistItems1>>>
    export type AddChecklistItems1MutationBody = ChecklistItem[]
    export type AddChecklistItems1MutationError = unknown

    export const useAddChecklistItems1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChecklistItems1>>, TError,{checklistId: number;data: ChecklistItem[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addChecklistItems1>>,
        TError,
        {checklistId: number;data: ChecklistItem[]},
        TContext
      > => {

      const mutationOptions = getAddChecklistItems1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const logLocationBatch = (
    locationLog: LocationLog[],
 signal?: AbortSignal
) => {
      
      
      return customInstance<LogLocationBatch200>(
      {url: `/api/driver/locations/batch-log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: locationLog, signal
    },
      );
    }
  


export const getLogLocationBatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext> => {

const mutationKey = ['logLocationBatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logLocationBatch>>, {data: LocationLog[]}> = (props) => {
          const {data} = props ?? {};

          return  logLocationBatch(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogLocationBatchMutationResult = NonNullable<Awaited<ReturnType<typeof logLocationBatch>>>
    export type LogLocationBatchMutationBody = LocationLog[]
    export type LogLocationBatchMutationError = unknown

    export const useLogLocationBatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logLocationBatch>>,
        TError,
        {data: LocationLog[]},
        TContext
      > => {

      const mutationOptions = getLogLocationBatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const login = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Login200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = unknown

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const streamDriverLocation = (
    params: StreamDriverLocationParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SseEmitter>(
      {url: `/api/manager/locations/stream`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getStreamDriverLocationQueryKey = (params?: StreamDriverLocationParams,) => {
    return [
    `/api/manager/locations/stream`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStreamDriverLocationQueryOptions = <TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStreamDriverLocationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof streamDriverLocation>>> = ({ signal }) => streamDriverLocation(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StreamDriverLocationQueryResult = NonNullable<Awaited<ReturnType<typeof streamDriverLocation>>>
export type StreamDriverLocationQueryError = unknown


export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamDriverLocation>>,
          TError,
          Awaited<ReturnType<typeof streamDriverLocation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamDriverLocation>>,
          TError,
          Awaited<ReturnType<typeof streamDriverLocation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStreamDriverLocationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getHistory = (
    params: GetHistoryParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DriverTripHistory[]>(
      {url: `/api/manager/locations/history`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetHistoryQueryKey = (params?: GetHistoryParams,) => {
    return [
    `/api/manager/locations/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({ signal }) => getHistory(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>
export type GetHistoryQueryError = unknown


export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const hello = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/manager/locations/hello`, method: 'GET', signal
    },
      );
    }
  



export const getHelloQueryKey = () => {
    return [
    `/api/manager/locations/hello`
    ] as const;
    }

    
export const getHelloQueryOptions = <TData = Awaited<ReturnType<typeof hello>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof hello>>> = ({ signal }) => hello(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HelloQueryResult = NonNullable<Awaited<ReturnType<typeof hello>>>
export type HelloQueryError = unknown


export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getChecklistItems = (
    checklistId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChecklistItem[]>(
      {url: `/api/manager/locations/checklist/${checklistId}/items`, method: 'GET', signal
    },
      );
    }
  



export const getGetChecklistItemsQueryKey = (checklistId?: number,) => {
    return [
    `/api/manager/locations/checklist/${checklistId}/items`
    ] as const;
    }

    
export const getGetChecklistItemsQueryOptions = <TData = Awaited<ReturnType<typeof getChecklistItems>>, TError = unknown>(checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChecklistItemsQueryKey(checklistId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChecklistItems>>> = ({ signal }) => getChecklistItems(checklistId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(checklistId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChecklistItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getChecklistItems>>>
export type GetChecklistItemsQueryError = unknown


export function useGetChecklistItems<TData = Awaited<ReturnType<typeof getChecklistItems>>, TError = unknown>(
 checklistId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChecklistItems>>,
          TError,
          Awaited<ReturnType<typeof getChecklistItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChecklistItems<TData = Awaited<ReturnType<typeof getChecklistItems>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChecklistItems>>,
          TError,
          Awaited<ReturnType<typeof getChecklistItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChecklistItems<TData = Awaited<ReturnType<typeof getChecklistItems>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetChecklistItems<TData = Awaited<ReturnType<typeof getChecklistItems>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklistItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChecklistItemsQueryOptions(checklistId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAllWorkers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<User[]>(
      {url: `/api/manager/locations/all-workers`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllWorkersQueryKey = () => {
    return [
    `/api/manager/locations/all-workers`
    ] as const;
    }

    
export const getGetAllWorkersQueryOptions = <TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllWorkersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllWorkers>>> = ({ signal }) => getAllWorkers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllWorkersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWorkers>>>
export type GetAllWorkersQueryError = unknown


export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWorkers>>,
          TError,
          Awaited<ReturnType<typeof getAllWorkers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWorkers>>,
          TError,
          Awaited<ReturnType<typeof getAllWorkers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllWorkersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAllChecklists = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Checklist[]>(
      {url: `/api/manager/locations/all-checklists`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllChecklistsQueryKey = () => {
    return [
    `/api/manager/locations/all-checklists`
    ] as const;
    }

    
export const getGetAllChecklistsQueryOptions = <TData = Awaited<ReturnType<typeof getAllChecklists>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllChecklistsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllChecklists>>> = ({ signal }) => getAllChecklists(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllChecklistsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllChecklists>>>
export type GetAllChecklistsQueryError = unknown


export function useGetAllChecklists<TData = Awaited<ReturnType<typeof getAllChecklists>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllChecklists>>,
          TError,
          Awaited<ReturnType<typeof getAllChecklists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllChecklists<TData = Awaited<ReturnType<typeof getAllChecklists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllChecklists>>,
          TError,
          Awaited<ReturnType<typeof getAllChecklists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllChecklists<TData = Awaited<ReturnType<typeof getAllChecklists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllChecklists<TData = Awaited<ReturnType<typeof getAllChecklists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllChecklists>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllChecklistsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getActiveDrivers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<number[]>(
      {url: `/api/manager/locations/active`, method: 'GET', signal
    },
      );
    }
  



export const getGetActiveDriversQueryKey = () => {
    return [
    `/api/manager/locations/active`
    ] as const;
    }

    
export const getGetActiveDriversQueryOptions = <TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveDriversQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveDrivers>>> = ({ signal }) => getActiveDrivers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveDriversQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveDrivers>>>
export type GetActiveDriversQueryError = unknown


export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveDrivers>>,
          TError,
          Awaited<ReturnType<typeof getActiveDrivers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveDrivers>>,
          TError,
          Awaited<ReturnType<typeof getActiveDrivers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveDriversQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const hello1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/driver/locations/hello`, method: 'GET', signal
    },
      );
    }
  



export const getHello1QueryKey = () => {
    return [
    `/api/driver/locations/hello`
    ] as const;
    }

    
export const getHello1QueryOptions = <TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHello1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof hello1>>> = ({ signal }) => hello1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Hello1QueryResult = NonNullable<Awaited<ReturnType<typeof hello1>>>
export type Hello1QueryError = unknown


export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello1>>,
          TError,
          Awaited<ReturnType<typeof hello1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello1>>,
          TError,
          Awaited<ReturnType<typeof hello1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHello1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const assignedChecklist = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Checklist[]>(
      {url: `/api/driver/locations/assigned-checklists`, method: 'GET', signal
    },
      );
    }
  



export const getAssignedChecklistQueryKey = () => {
    return [
    `/api/driver/locations/assigned-checklists`
    ] as const;
    }

    
export const getAssignedChecklistQueryOptions = <TData = Awaited<ReturnType<typeof assignedChecklist>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssignedChecklistQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof assignedChecklist>>> = ({ signal }) => assignedChecklist(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssignedChecklistQueryResult = NonNullable<Awaited<ReturnType<typeof assignedChecklist>>>
export type AssignedChecklistQueryError = unknown


export function useAssignedChecklist<TData = Awaited<ReturnType<typeof assignedChecklist>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignedChecklist>>,
          TError,
          Awaited<ReturnType<typeof assignedChecklist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignedChecklist<TData = Awaited<ReturnType<typeof assignedChecklist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignedChecklist>>,
          TError,
          Awaited<ReturnType<typeof assignedChecklist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignedChecklist<TData = Awaited<ReturnType<typeof assignedChecklist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssignedChecklist<TData = Awaited<ReturnType<typeof assignedChecklist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssignedChecklistQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const assignedChecklist1 = (
    checklistId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChecklistItem[]>(
      {url: `/api/driver/locations/assigned-checklists/${checklistId}`, method: 'GET', signal
    },
      );
    }
  



export const getAssignedChecklist1QueryKey = (checklistId?: number,) => {
    return [
    `/api/driver/locations/assigned-checklists/${checklistId}`
    ] as const;
    }

    
export const getAssignedChecklist1QueryOptions = <TData = Awaited<ReturnType<typeof assignedChecklist1>>, TError = unknown>(checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssignedChecklist1QueryKey(checklistId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof assignedChecklist1>>> = ({ signal }) => assignedChecklist1(checklistId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(checklistId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssignedChecklist1QueryResult = NonNullable<Awaited<ReturnType<typeof assignedChecklist1>>>
export type AssignedChecklist1QueryError = unknown


export function useAssignedChecklist1<TData = Awaited<ReturnType<typeof assignedChecklist1>>, TError = unknown>(
 checklistId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignedChecklist1>>,
          TError,
          Awaited<ReturnType<typeof assignedChecklist1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignedChecklist1<TData = Awaited<ReturnType<typeof assignedChecklist1>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignedChecklist1>>,
          TError,
          Awaited<ReturnType<typeof assignedChecklist1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignedChecklist1<TData = Awaited<ReturnType<typeof assignedChecklist1>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssignedChecklist1<TData = Awaited<ReturnType<typeof assignedChecklist1>>, TError = unknown>(
 checklistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignedChecklist1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssignedChecklist1QueryOptions(checklistId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteChecklist = (
    checklistId: number,
 ) => {
      
      
      return customInstance<DeleteChecklist200>(
      {url: `/api/manager/locations/checklist/${checklistId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteChecklistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklist>>, TError,{checklistId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteChecklist>>, TError,{checklistId: number}, TContext> => {

const mutationKey = ['deleteChecklist'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChecklist>>, {checklistId: number}> = (props) => {
          const {checklistId} = props ?? {};

          return  deleteChecklist(checklistId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChecklistMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChecklist>>>
    
    export type DeleteChecklistMutationError = unknown

    export const useDeleteChecklist = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklist>>, TError,{checklistId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChecklist>>,
        TError,
        {checklistId: number},
        TContext
      > => {

      const mutationOptions = getDeleteChecklistMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const deleteChecklistItems1 = (
    checklistId: number,
    itemId: number,
 ) => {
      
      
      return customInstance<DeleteChecklistItems1200>(
      {url: `/api/manager/locations/checklist/${checklistId}/delete-item/${itemId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteChecklistItems1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems1>>, TError,{checklistId: number;itemId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems1>>, TError,{checklistId: number;itemId: number}, TContext> => {

const mutationKey = ['deleteChecklistItems1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChecklistItems1>>, {checklistId: number;itemId: number}> = (props) => {
          const {checklistId,itemId} = props ?? {};

          return  deleteChecklistItems1(checklistId,itemId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChecklistItems1MutationResult = NonNullable<Awaited<ReturnType<typeof deleteChecklistItems1>>>
    
    export type DeleteChecklistItems1MutationError = unknown

    export const useDeleteChecklistItems1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChecklistItems1>>, TError,{checklistId: number;itemId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChecklistItems1>>,
        TError,
        {checklistId: number;itemId: number},
        TContext
      > => {

      const mutationOptions = getDeleteChecklistItems1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
