/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
export interface LocationLog {
  id?: number;
  tripId?: number;
  latitude?: number;
  longitude?: number;
  recordedAt?: string;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

export interface SseEmitter {
  timeout?: number;
}

export interface DriverTripHistory {
  userId?: number;
  trips?: TripHistory[];
}

export interface LocationLogDTO {
  latitude?: number;
  longitude?: number;
}

export interface TripHistory {
  tripId?: number;
  logs?: LocationLogDTO[];
}

export interface User {
  id?: number;
  name?: string;
  phoneNumber?: string;
  passwordHash?: string;
}

export type RegisterWorkerBody = {[key: string]: string};

export type RegisterWorker200 = { [key: string]: unknown };

export type StartTrip200 = { [key: string]: unknown };

export type LogLocation200 = { [key: string]: unknown };

export type EndTrip200 = { [key: string]: unknown };

export type LogLocationBatch200 = { [key: string]: unknown };

export type Login200 = { [key: string]: unknown };

export type StreamDriverLocationParams = {
userId: number;
};

export type GetHistoryParams = {
userIds: number[];
start: string;
end: string;
};

export const registerWorker = (
    registerWorkerBody: RegisterWorkerBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterWorker200>(
      {url: `/api/manager/locations/register-worker`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerWorkerBody, signal
    },
      );
    }
  


export const getRegisterWorkerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext> => {

const mutationKey = ['registerWorker'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWorker>>, {data: RegisterWorkerBody}> = (props) => {
          const {data} = props ?? {};

          return  registerWorker(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWorkerMutationResult = NonNullable<Awaited<ReturnType<typeof registerWorker>>>
    export type RegisterWorkerMutationBody = RegisterWorkerBody
    export type RegisterWorkerMutationError = unknown

    export const useRegisterWorker = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWorker>>, TError,{data: RegisterWorkerBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerWorker>>,
        TError,
        {data: RegisterWorkerBody},
        TContext
      > => {

      const mutationOptions = getRegisterWorkerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const startTrip = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<StartTrip200>(
      {url: `/api/driver/locations/start`, method: 'POST', signal
    },
      );
    }
  


export const getStartTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext> => {

const mutationKey = ['startTrip'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startTrip>>, void> = () => {
          

          return  startTrip()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartTripMutationResult = NonNullable<Awaited<ReturnType<typeof startTrip>>>
    
    export type StartTripMutationError = unknown

    export const useStartTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTrip>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startTrip>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStartTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const logLocation = (
    locationLog: LocationLog,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LogLocation200>(
      {url: `/api/driver/locations/log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: locationLog, signal
    },
      );
    }
  


export const getLogLocationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext> => {

const mutationKey = ['logLocation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logLocation>>, {data: LocationLog}> = (props) => {
          const {data} = props ?? {};

          return  logLocation(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogLocationMutationResult = NonNullable<Awaited<ReturnType<typeof logLocation>>>
    export type LogLocationMutationBody = LocationLog
    export type LogLocationMutationError = unknown

    export const useLogLocation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocation>>, TError,{data: LocationLog}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logLocation>>,
        TError,
        {data: LocationLog},
        TContext
      > => {

      const mutationOptions = getLogLocationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const endTrip = (
    tripId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<EndTrip200>(
      {url: `/api/driver/locations/end/${tripId}`, method: 'POST', signal
    },
      );
    }
  


export const getEndTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext> => {

const mutationKey = ['endTrip'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof endTrip>>, {tripId: number}> = (props) => {
          const {tripId} = props ?? {};

          return  endTrip(tripId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EndTripMutationResult = NonNullable<Awaited<ReturnType<typeof endTrip>>>
    
    export type EndTripMutationError = unknown

    export const useEndTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endTrip>>, TError,{tripId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof endTrip>>,
        TError,
        {tripId: number},
        TContext
      > => {

      const mutationOptions = getEndTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const logLocationBatch = (
    locationLog: LocationLog[],
 signal?: AbortSignal
) => {
      
      
      return customInstance<LogLocationBatch200>(
      {url: `/api/driver/locations/batch-log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: locationLog, signal
    },
      );
    }
  


export const getLogLocationBatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext> => {

const mutationKey = ['logLocationBatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logLocationBatch>>, {data: LocationLog[]}> = (props) => {
          const {data} = props ?? {};

          return  logLocationBatch(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogLocationBatchMutationResult = NonNullable<Awaited<ReturnType<typeof logLocationBatch>>>
    export type LogLocationBatchMutationBody = LocationLog[]
    export type LogLocationBatchMutationError = unknown

    export const useLogLocationBatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logLocationBatch>>, TError,{data: LocationLog[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logLocationBatch>>,
        TError,
        {data: LocationLog[]},
        TContext
      > => {

      const mutationOptions = getLogLocationBatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const login = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Login200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = unknown

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const streamDriverLocation = (
    params: StreamDriverLocationParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SseEmitter>(
      {url: `/api/manager/locations/stream`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getStreamDriverLocationQueryKey = (params?: StreamDriverLocationParams,) => {
    return [
    `/api/manager/locations/stream`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStreamDriverLocationQueryOptions = <TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStreamDriverLocationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof streamDriverLocation>>> = ({ signal }) => streamDriverLocation(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StreamDriverLocationQueryResult = NonNullable<Awaited<ReturnType<typeof streamDriverLocation>>>
export type StreamDriverLocationQueryError = unknown


export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamDriverLocation>>,
          TError,
          Awaited<ReturnType<typeof streamDriverLocation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamDriverLocation>>,
          TError,
          Awaited<ReturnType<typeof streamDriverLocation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStreamDriverLocation<TData = Awaited<ReturnType<typeof streamDriverLocation>>, TError = unknown>(
 params: StreamDriverLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamDriverLocation>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStreamDriverLocationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getHistory = (
    params: GetHistoryParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DriverTripHistory[]>(
      {url: `/api/manager/locations/history`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetHistoryQueryKey = (params?: GetHistoryParams,) => {
    return [
    `/api/manager/locations/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({ signal }) => getHistory(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>
export type GetHistoryQueryError = unknown


export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const hello = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/manager/locations/hello`, method: 'GET', signal
    },
      );
    }
  



export const getHelloQueryKey = () => {
    return [
    `/api/manager/locations/hello`
    ] as const;
    }

    
export const getHelloQueryOptions = <TData = Awaited<ReturnType<typeof hello>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof hello>>> = ({ signal }) => hello(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HelloQueryResult = NonNullable<Awaited<ReturnType<typeof hello>>>
export type HelloQueryError = unknown


export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAllWorkers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<User[]>(
      {url: `/api/manager/locations/all-workers`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllWorkersQueryKey = () => {
    return [
    `/api/manager/locations/all-workers`
    ] as const;
    }

    
export const getGetAllWorkersQueryOptions = <TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllWorkersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllWorkers>>> = ({ signal }) => getAllWorkers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllWorkersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWorkers>>>
export type GetAllWorkersQueryError = unknown


export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWorkers>>,
          TError,
          Awaited<ReturnType<typeof getAllWorkers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWorkers>>,
          TError,
          Awaited<ReturnType<typeof getAllWorkers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllWorkers<TData = Awaited<ReturnType<typeof getAllWorkers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWorkers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllWorkersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getActiveDrivers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<number[]>(
      {url: `/api/manager/locations/active`, method: 'GET', signal
    },
      );
    }
  



export const getGetActiveDriversQueryKey = () => {
    return [
    `/api/manager/locations/active`
    ] as const;
    }

    
export const getGetActiveDriversQueryOptions = <TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveDriversQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveDrivers>>> = ({ signal }) => getActiveDrivers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveDriversQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveDrivers>>>
export type GetActiveDriversQueryError = unknown


export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveDrivers>>,
          TError,
          Awaited<ReturnType<typeof getActiveDrivers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveDrivers>>,
          TError,
          Awaited<ReturnType<typeof getActiveDrivers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetActiveDrivers<TData = Awaited<ReturnType<typeof getActiveDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveDrivers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveDriversQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const hello1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/driver/locations/hello`, method: 'GET', signal
    },
      );
    }
  



export const getHello1QueryKey = () => {
    return [
    `/api/driver/locations/hello`
    ] as const;
    }

    
export const getHello1QueryOptions = <TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHello1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof hello1>>> = ({ signal }) => hello1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Hello1QueryResult = NonNullable<Awaited<ReturnType<typeof hello1>>>
export type Hello1QueryError = unknown


export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello1>>,
          TError,
          Awaited<ReturnType<typeof hello1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello1>>,
          TError,
          Awaited<ReturnType<typeof hello1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHello1<TData = Awaited<ReturnType<typeof hello1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHello1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
